### ISSUE TITLE
执行user_info.py 发生错误

### ISSUE THREAD

**Issue by shyboy** [catbaron0/respawnWeibo#1]
$ python3 user_info.py 
Traceback (most recent call last):
  File "user_info.py", line 3, in <module>
    from weibo.weibo_login import wblogin
  File "/Users/sunshy/code/project/respawnWeibo/weibo/weibo_login.py", line 7, in <module>
    import rsa
ModuleNotFoundError: No module named 'rsa'

**Comment by shyboy** [comment]
使用 pip3 install rsa 后成功了
