### ISSUE TITLE
语法相关问题

### ISSUE THREAD

**Issue by 5renyuebing** [catbaron0/respawnWeibo#2]
作者你好，想问一下这里的冒号是符合python语法吗？我的python3报错了
![微信图片_20200614184104](https://user-images.githubusercontent.com/32872430/84591210-28f57800-ae6f-11ea-8101-a12dcf57c2c8.png)

**Comment by catbaron0** [comment]
> 作者你好，想问一下这里的冒号是符合python语法吗？我的python3报错了
> 
> ![微信图片_20200614184104](https://user-images.githubusercontent.com/32872430/84591210-28f57800-ae6f-11ea-8101-a12dcf57c2c8.png)
> 
> 
> 
> 

这个冒号的写法应该是被Python3支持的。具体的错误是什么？

**Comment by lcxwasn** [comment]
运行提示错误是怎么回事
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\respawnWeibo-master\respawnWeibo-master\user_info.py", line 7, in <module>
    session, uid = wblogin()
  File "C:\Users\Administrator\Desktop\respawnWeibo-master\respawnWeibo-master\weibo\weibo_login.py", line 45, in wblogin
    'servertime': pre_login['servertime'] ,
KeyError: 'servertime'

**Comment by BigbigShark** [comment]
> 

我也遇到了这个问题

**Comment by BigbigShark** [comment]
> 

我也遇到了这个问题

**Comment by catbaron0** [comment]
@BigbigShark 这个错误应该是微博修改了API导致的。所以这个项目暂时不可用了
